GET http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMyIsImlkIjoiNjcyYmUwMTVhYmVhMjE4MmFlMWM0NTVmIiwiaWF0IjoxNzMwOTMwNTM4LCJleHAiOjE3MzA5MzQxMzh9.dUbm535HO2IcvsVp0m_HwHnpzOUbb6D0sPNkM8sunkM