POST http://localhost:3003/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMyIsImlkIjoiNjcyYmUwMTVhYmVhMjE4MmFlMWM0NTVmIiwiaWF0IjoxNzMwOTMwNTM4LCJleHAiOjE3MzA5MzQxMzh9.dUbm535HO2IcvsVp0m_HwHnpzOUbb6D0sPNkM8sunkM

{
  "username": "testuser5",
  "password": "contraseñaSegura1234",
  "name": "Bebe Morita"
}